// Supabase 테이블 붙기 전까지 화면을 채우는 더미데이터 모음. 실제 데이터 연동 시 이 파일째로 삭제.
import { type Song } from './playlistTypes';

const USER_NAMES = ['이줄', '민지', '수진', '준호', '태희', '성은', '다영', '호진', '지은', '명준', '민준', '혜원', '기범', '소연', '주현'];
const USER_COMMENTS = [
  '이 노래 진짜 좋아! 베이스가 미쳤어 내인생 이런 R&B는 처음이야 ㅠㅠ',
  '요즘 내 감성이야 ✨',
  '반복 재생 중...',
  '이렇게 좋은 곡이 있다니',
  '감성 만렙 💯',
  '매일 듣고 있어요',
  '이 가수 팬입니다! 🎤',
  '최고의 선택 👍',
  '중독성 있어요',
  '찐 명곡',
  '무한재생',
  '요즘 탈출곡',
  '혼자만 알고싶던 곡',
  '신곡 좋네요',
  '이 아티스트 완전 사랑해 진짜 너무너무너무너무너무너무너무 사랑해',
];

function getRandomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomUserId(): number {
  return Math.floor(Math.random() * 30) + 1;
}

export const DUMMY_SONGS: Song[] = [
  {
    trackId: '5eBM5qATb1IfJvNzGuS2GX',
    title: 'Busy Boy',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 245,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '3c0anSTjsn20lztbBmZt03',
    title: '미장원',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 187,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '0kt2S0FV9DEGIOg247sT8b',
    title: '미친건가',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 176,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '4uh6rj3FryYQXMz9zLqDKL',
    title: 'Fly away',
    artist: '권진아',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273bee4779793a1d10af6e8bd4f',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 165,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '171mGT1HdxM2HdqZrWNY31',
    title: '다큐멘터리',
    artist: '윤마치',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b2734c02aacdf6281db79169e115',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 265,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '3aK5mtd4CKxLF6RpC1doh6',
    title: '마음으로',
    artist: '유다빈밴드',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273598f97c45eee469199fd0733',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['발라드'],
    heartCount: 243,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '6W4iF5kAqqwKiVwAk3TcN1',
    title: '하루에 한번씩',
    artist: '거니',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b27382e910c061e1c7555a02a266',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 221,
    previewUrl: '',
    createdAt: new Date(),
  },
];

export const DUMMY_CHART: Song[] = [
  {
    trackId: '3Q3wWJxr6sBt8afP9hJj4J',
    title: 'LOVE SONG',
    artist: '유다빈밴드',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273fd07915694e0ffb3b961a7b5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 298,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '4Qqd4mzQzVGpvPrzq3Dtn8',
    title: '초록',
    artist: '윤마치',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273da16a8d501f1621068b0ea8b',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 287,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '5eBM5qATb1IfJvNzGuS2GX',
    title: 'Busy Boy',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 276,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '171mGT1HdxM2HdqZrWNY31',
    title: '다큐멘터리',
    artist: '윤마치',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b2734c02aacdf6281db79169e115',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 265,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '3c0anSTjsn20lztbBmZt03',
    title: '미장원',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 254,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '0kt2S0FV9DEGIOg247sT8b',
    title: '미친건가',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 243,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '4uh6rj3FryYQXMz9zLqDKL',
    title: 'Fly away',
    artist: '권진아',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273bee4779793a1d10af6e8bd4f',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['인디'],
    heartCount: 232,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '6W4iF5kAqqwKiVwAk3TcN1',
    title: '하루에 한번씩',
    artist: '거니',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b27382e910c061e1c7555a02a266',
    userProfile: { name: getRandomElement(USER_NAMES), avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=user${getRandomUserId()}` },
    comment: getRandomElement(USER_COMMENTS),
    genres: ['R&B'],
    heartCount: 221,
    previewUrl: '',
    createdAt: new Date(),
  },
];

export const DUMMY_LIKED_SONGS: Song[] = [
  {
    trackId: '5eBM5qATb1IfJvNzGuS2GX',
    title: 'Busy Boy',
    artist: '주혜린',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273951f05b855b09c8b4d7d2ee5',
    userProfile: { name: '민지', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked1' },
    comment: '완전 내 최애곡',
    genres: ['R&B'],
    heartCount: 312,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '3Q3wWJxr6sBt8afP9hJj4J',
    title: 'LOVE SONG',
    artist: '유다빈밴드',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273fd07915694e0ffb3b961a7b5',
    userProfile: { name: '태희', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked2' },
    comment: '노래방 필수곡',
    genres: ['인디'],
    heartCount: 289,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '171mGT1HdxM2HdqZrWNY31',
    title: '다큐멘터리',
    artist: '윤마치',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b2734c02aacdf6281db79169e115',
    userProfile: { name: '성은', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked3' },
    comment: '가사가 진짜 좋아요',
    genres: ['인디'],
    heartCount: 241,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '4uh6rj3FryYQXMz9zLqDKL',
    title: 'Fly away',
    artist: '권진아',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273bee4779793a1d10af6e8bd4f',
    userProfile: { name: '기범', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked4' },
    comment: '드라이브할 때 딱',
    genres: ['인디'],
    heartCount: 198,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '6W4iF5kAqqwKiVwAk3TcN1',
    title: '하루에 한번씩',
    artist: '거니',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b27382e910c061e1c7555a02a266',
    userProfile: { name: '준호', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked6' },
    comment: '매일 듣는 중',
    genres: ['R&B'],
    heartCount: 154,
    previewUrl: '',
    createdAt: new Date(),
  },
  {
    trackId: '4Qqd4mzQzVGpvPrzq3Dtn8',
    title: '초록',
    artist: '윤마치',
    albumArtUrl: 'https://i.scdn.co/image/ab67616d0000b273da16a8d501f1621068b0ea8b',
    userProfile: { name: '지은', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liked7' },
    comment: '분위기 최고',
    genres: ['인디'],
    heartCount: 132,
    previewUrl: '',
    createdAt: new Date(),
  },
];
