create extension if not exists "pg_net" with schema "public";


  create table "public"."app_config" (
    "id" integer not null default 1,
    "current_period_override" text,
    "period_schedule" jsonb not null default '[]'::jsonb,
    "custom_holidays" jsonb not null default '[]'::jsonb,
    "force_weekend" boolean not null default false,
    "no_operation_days" jsonb not null default '[]'::jsonb,
    "force_no_operation" boolean not null default false
      );


alter table "public"."app_config" enable row level security;


  create table "public"."banners" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "image_url" text not null,
    "alt_text" text,
    "click_url" text,
    "display_order" integer default 0,
    "is_active" boolean default true
      );


alter table "public"."banners" enable row level security;


  create table "public"."devices" (
    "id" uuid not null,
    "fcm_token" text not null,
    "platform" text,
    "last_active_at" timestamp with time zone default now(),
    "created_at" timestamp with time zone default now()
      );


alter table "public"."devices" enable row level security;


  create table "public"."feedbacks" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "content" text not null,
    "platform" text default 'web'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."feedbacks" enable row level security;


  create table "public"."subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "device_id" uuid,
    "topic" text not null,
    "params" jsonb default '{}'::jsonb,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."subscriptions" enable row level security;

CREATE UNIQUE INDEX app_config_pkey ON public.app_config USING btree (id);

CREATE UNIQUE INDEX banners_pkey ON public.banners USING btree (id);

CREATE UNIQUE INDEX devices_fcm_token_key ON public.devices USING btree (fcm_token);

CREATE UNIQUE INDEX devices_pkey ON public.devices USING btree (id);

CREATE UNIQUE INDEX feedbacks_pkey ON public.feedbacks USING btree (id);

CREATE INDEX idx_subscriptions_device_id ON public.subscriptions USING btree (device_id);

CREATE INDEX idx_subscriptions_topic ON public.subscriptions USING btree (topic);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX unique_device_topic ON public.subscriptions USING btree (device_id, topic);

alter table "public"."app_config" add constraint "app_config_pkey" PRIMARY KEY using index "app_config_pkey";

alter table "public"."banners" add constraint "banners_pkey" PRIMARY KEY using index "banners_pkey";

alter table "public"."devices" add constraint "devices_pkey" PRIMARY KEY using index "devices_pkey";

alter table "public"."feedbacks" add constraint "feedbacks_pkey" PRIMARY KEY using index "feedbacks_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."devices" add constraint "devices_fcm_token_key" UNIQUE using index "devices_fcm_token_key";

alter table "public"."feedbacks" add constraint "feedbacks_content_check" CHECK ((char_length(TRIM(BOTH FROM content)) >= 5)) not valid;

alter table "public"."feedbacks" validate constraint "feedbacks_content_check";

alter table "public"."feedbacks" add constraint "feedbacks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."feedbacks" validate constraint "feedbacks_user_id_fkey";

alter table "public"."subscriptions" add constraint "subscriptions_device_id_fkey" FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_device_id_fkey";

alter table "public"."subscriptions" add constraint "unique_device_topic" UNIQUE using index "unique_device_topic";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_alarm_subscription(p_device_id uuid, p_topic text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_sub jsonb;
BEGIN
  -- 🚨 [IDOR 해킹 방지] 토큰 소유주 유효성 검증 가드 추가
  IF auth.uid() <> p_device_id THEN
    RAISE EXCEPTION 'Unauthorized: You do not own this device';
  END IF;

  SELECT jsonb_build_object(
    'is_active', is_active,
    'params', params
  )
  INTO v_sub
  FROM public.subscriptions
  WHERE device_id = p_device_id AND topic = p_topic;

  RETURN v_sub;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_alarm_subscription(p_device_id uuid, p_fcm_token text, p_topic text, p_params jsonb, p_is_active boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- 1) FCM 토큰이 전달된 경우 Devices 테이블 갱신
  IF p_fcm_token IS NOT NULL THEN
    INSERT INTO public.devices (id, fcm_token, platform, last_active_at)
    VALUES (p_device_id, p_fcm_token, 'web', now())
    ON CONFLICT (id) DO UPDATE
    SET fcm_token = EXCLUDED.fcm_token,
        last_active_at = now();
  END IF;

  -- 2) Subscriptions 테이블 갱신
  INSERT INTO public.subscriptions (device_id, topic, params, is_active)
  VALUES (p_device_id, p_topic, p_params, p_is_active)
  ON CONFLICT (device_id, topic) DO UPDATE
  SET params = COALESCE(p_params, subscriptions.params),
      is_active = p_is_active,
      updated_at = now();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_alarm_subscription(p_device_id uuid, p_fcm_token text, p_topic text, p_params jsonb, p_is_active boolean, p_platform text DEFAULT 'web'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- 🚨 [IDOR 해킹 방지] 토큰 소유주 유효성 검증 가드 추가
  IF auth.uid() <> p_device_id THEN
    RAISE EXCEPTION 'Unauthorized: You do not own this device';
  END IF;

  -- 1) FCM 토큰이 전달된 경우 Devices 테이블 갱신
  IF p_fcm_token IS NOT NULL THEN
    INSERT INTO public.devices (id, fcm_token, platform, last_active_at)
    VALUES (p_device_id, p_fcm_token, COALESCE(p_platform, 'web'), now())
    ON CONFLICT (id) DO UPDATE
    SET fcm_token = EXCLUDED.fcm_token,
        platform = COALESCE(EXCLUDED.platform, devices.platform),
        last_active_at = now();
  END IF;

  -- 2) Subscriptions 테이블 갱신
  INSERT INTO public.subscriptions (device_id, topic, params, is_active)
  VALUES (p_device_id, p_topic, p_params, p_is_active)
  ON CONFLICT (device_id, topic) DO UPDATE
  SET params = COALESCE(p_params, subscriptions.params),
      is_active = p_is_active,
      updated_at = now();
END;
$function$
;

grant delete on table "public"."app_config" to "anon";

grant insert on table "public"."app_config" to "anon";

grant references on table "public"."app_config" to "anon";

grant select on table "public"."app_config" to "anon";

grant trigger on table "public"."app_config" to "anon";

grant truncate on table "public"."app_config" to "anon";

grant update on table "public"."app_config" to "anon";

grant delete on table "public"."app_config" to "authenticated";

grant insert on table "public"."app_config" to "authenticated";

grant references on table "public"."app_config" to "authenticated";

grant select on table "public"."app_config" to "authenticated";

grant trigger on table "public"."app_config" to "authenticated";

grant truncate on table "public"."app_config" to "authenticated";

grant update on table "public"."app_config" to "authenticated";

grant delete on table "public"."app_config" to "service_role";

grant insert on table "public"."app_config" to "service_role";

grant references on table "public"."app_config" to "service_role";

grant select on table "public"."app_config" to "service_role";

grant trigger on table "public"."app_config" to "service_role";

grant truncate on table "public"."app_config" to "service_role";

grant update on table "public"."app_config" to "service_role";

grant delete on table "public"."banners" to "anon";

grant insert on table "public"."banners" to "anon";

grant references on table "public"."banners" to "anon";

grant select on table "public"."banners" to "anon";

grant trigger on table "public"."banners" to "anon";

grant truncate on table "public"."banners" to "anon";

grant update on table "public"."banners" to "anon";

grant delete on table "public"."banners" to "authenticated";

grant insert on table "public"."banners" to "authenticated";

grant references on table "public"."banners" to "authenticated";

grant select on table "public"."banners" to "authenticated";

grant trigger on table "public"."banners" to "authenticated";

grant truncate on table "public"."banners" to "authenticated";

grant update on table "public"."banners" to "authenticated";

grant delete on table "public"."banners" to "service_role";

grant insert on table "public"."banners" to "service_role";

grant references on table "public"."banners" to "service_role";

grant select on table "public"."banners" to "service_role";

grant trigger on table "public"."banners" to "service_role";

grant truncate on table "public"."banners" to "service_role";

grant update on table "public"."banners" to "service_role";

grant delete on table "public"."devices" to "anon";

grant insert on table "public"."devices" to "anon";

grant references on table "public"."devices" to "anon";

grant select on table "public"."devices" to "anon";

grant trigger on table "public"."devices" to "anon";

grant truncate on table "public"."devices" to "anon";

grant update on table "public"."devices" to "anon";

grant delete on table "public"."devices" to "authenticated";

grant insert on table "public"."devices" to "authenticated";

grant references on table "public"."devices" to "authenticated";

grant select on table "public"."devices" to "authenticated";

grant trigger on table "public"."devices" to "authenticated";

grant truncate on table "public"."devices" to "authenticated";

grant update on table "public"."devices" to "authenticated";

grant delete on table "public"."devices" to "service_role";

grant insert on table "public"."devices" to "service_role";

grant references on table "public"."devices" to "service_role";

grant select on table "public"."devices" to "service_role";

grant trigger on table "public"."devices" to "service_role";

grant truncate on table "public"."devices" to "service_role";

grant update on table "public"."devices" to "service_role";

grant delete on table "public"."feedbacks" to "anon";

grant insert on table "public"."feedbacks" to "anon";

grant references on table "public"."feedbacks" to "anon";

grant select on table "public"."feedbacks" to "anon";

grant trigger on table "public"."feedbacks" to "anon";

grant truncate on table "public"."feedbacks" to "anon";

grant update on table "public"."feedbacks" to "anon";

grant delete on table "public"."feedbacks" to "authenticated";

grant insert on table "public"."feedbacks" to "authenticated";

grant references on table "public"."feedbacks" to "authenticated";

grant select on table "public"."feedbacks" to "authenticated";

grant trigger on table "public"."feedbacks" to "authenticated";

grant truncate on table "public"."feedbacks" to "authenticated";

grant update on table "public"."feedbacks" to "authenticated";

grant delete on table "public"."feedbacks" to "service_role";

grant insert on table "public"."feedbacks" to "service_role";

grant references on table "public"."feedbacks" to "service_role";

grant select on table "public"."feedbacks" to "service_role";

grant trigger on table "public"."feedbacks" to "service_role";

grant truncate on table "public"."feedbacks" to "service_role";

grant update on table "public"."feedbacks" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";


  create policy "Enable read access for all users"
  on "public"."app_config"
  as permissive
  for select
  to public
using (true);



  create policy "누구나 배너를 조회할 수 있습니다."
  on "public"."banners"
  as permissive
  for select
  to public
using (true);



  create policy "Allow authenticated users to insert feedback"
  on "public"."feedbacks"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



